from selenium import webdriver
import time
driver = webdriver.Chrome()
driver.get('https://mgmt.ent-dev.kuban.io/')
driver.find_element_by_id('phone_num').send_keys('15566778899')
time.sleep(2)
driver.find_element_by_id('login_sms_code').send_keys('123456')
driver.find_element_by_xpath('//*[@id="root"]/div/div/div/form/div/div/div[2]/div[2]/div/div/span/button').click()
time.sleep(16)
driver.find_element_by_xpath('//button[@type="button"]').click()
time.sleep(1)
driver.find_element_by_id('name').send_keys('自动化分店')
driver.find_element_by_xpath('//*[@id="province_id"]/div/div/div').click()
time.sleep(3)
driver.find_element_by_xpath('//*[@role="listbox"]/li[1]').click()
time.sleep(3)
# driver.find_element_by_xpath('//*[@id="physical_address"]/div/div/ul/li/div/input').send_keys('北京市')
# time.sleep(2)
driver.find_element_by_xpath('//*[@id="manager_id"]/div/div').click()
time.sleep(2)
driver.find_element_by_xpath('//*[@id="manager_id"]/div/div/div[1]').send_keys('孟令全')
time.sleep(2)
# driver.find_element_by_xpath('//*[@role="listbox"]/li[1]').click()
# driver.find_element_by_xpath('//button[@type="submit"]').click()
time.sleep(3)

driver.close()