from selenium import webdriver
import time
driver = webdriver.Chrome()
driver.get('https://mgmt.ent-dev.kuban.io/')
driver.find_element_by_id('phone_num').send_keys('14443543545')
time.sleep(2)
driver.find_element_by_id('login_sms_code').send_keys('123456')
driver.find_element_by_xpath('//*[@id="root"]/div/div/div/form/div/div/div[2]/div[2]/div/div/span/button').click()
time.sleep(13)
driver.find_element_by_xpath('//*[@class="ant-layout-sider-children"]/ul/li[4]').click()
time.sleep(1)
try:
    driver.find_element_by_xpath('//*[@id="/locations/meeting$Menu"]/li[2]').click()
    time.sleep(1)
except:
    print('meizhaodao')
driver.find_element_by_xpath('//button[@type="button"]').click()
time.sleep(1)
driver.find_element_by_id('name').send_keys('selefangj')
driver.find_element_by_xpath('//*[@id="floor_info_id"]/div/div/div').click()
time.sleep(3)
# driver.find_element_by_xpath('//*[@id="d662aed9-bcc1-4b81-c506-408f709f7242"]/ul/li[2]').click()
# time.sleep(1)
driver.find_element_by_id('capacity').send_keys('123123')
driver.find_element_by_id('size').send_keys('32')
driver.find_element_by_xpath('//*[@type="submit"]').click()
time.sleep(3)
driver.close()