from selenium import webdriver
import time
driver = webdriver.Chrome()
driver.get('https://mgmt.ent-dev.kuban.io/')
driver.find_element_by_id('phone_num').send_keys('18293988402')
time.sleep(2)
driver.find_element_by_id('login_sms_code').send_keys('123456')
driver.find_element_by_xpath('//*[@id="root"]/div/div/div/form/div/div/div[2]/div[2]/div/div/span/button').click()
time.sleep(16)
driver.find_element_by_xpath('//*[@id="sider"]/div/ul/li[3]/div').click()
time.sleep(1)
driver.find_element_by_xpath('//*[@id="/locations/meeting$Menu"]/li[1]').click()
time.sleep(3)
driver.find_element_by_xpath('//*[@id="root"]/div/section/section/main/div/div[2]/div/div/div/div[2]/div/div/div/div[2]/div/table/tbody/tr[2]/td[2]/div/table/tbody/tr[2]/td[37]').click()
time.sleep(3)
txt = driver.find_element_by_xpath('/html/body/div[4]/div/div[2]/div/div/div[2]/form/div[1]/div/div/div[1]/div/div/span/div[1]/div/div[2]/div/span').text
# txt = driver.find_element_by_xpath('/html/body/div[4]/div/div[2]/div/div/div[2]/form/div[1]/div/div/div[1]/div/div/span/div[1]/div/div[2]/div/span/span/div/input').text
print(txt)
time.sleep(4)
driver.find_element_by_id('meeting_title').send_keys('自动化哦')
# driver.find_element_by_xpath('/html/body/div[7]/div/div[2]/div/div/div[2]/form/div[1]/div/div/label[1]/span[1]').click()
driver.find_element_by_xpath('/html/body/div[4]/div/div[2]/div/div/div[2]/form/div[1]/div/div/label[1]/span[2]/span').click()
driver.find_element_by_xpath('/html/body/div[4]/div/div[2]/div/div/div[2]/form/div[1]/div/div/div[4]/div[2]/div').click()
# driver.find_element_by_xpath('/html/body/div[4]/div/div[2]/div/div/div[2]/form/div[1]/div/div/div[4]/div[2]/div').send_keys('孟令全')
driver.find_element_by_id('topics').send_keys('这是会议议题哦')
# driver.find_element_by_xpath('/html/body/div[4]/div/div[2]/div/div/div[2]/form/div[1]/div/div/div[6]/a[6]').click()
time.sleep(2)
# driver.find_element_by_xpath('/html/body/div[4]/div/div[2]/div/div/div[2]/form/div[1]/div/div/div[6]/div[2]/div/span/div/button').click()
time.sleep(2)
# driver.find_element_by_xpath('/html/body/div[6]/div/div[2]/div/div/div[2]/div[1]/div/div/div[1]/div/div[2]').click()
# driver.find_element_by_xpath('/html/body/div[6]/div/div[2]/div/div/div[2]/div[2]/button[2]').click()
print('点击确认')
# driver.find_element_by_xpath('/html/body/div[8]/div/div[2]/div/div[2]/div/div/div[2]/button[2]').click()
# driver.find_element_by_xpath("//button[@class='ant-btn ant-btn-primary']").click()
print('二次确认')
time.sleep(2)
# driver.find_element_by_xpath('/html/body/div[4]/div/div[2]/div/div/div[2]/form/div[2]/button[2]').click()

# try:
#     text = driver.find_element_by_xpath('//*[@id="root"]/div/div/div/p').text
#     print(text)
# except:
#     print('aaaa')
time.sleep(4)
# driver.find_element_by_xpath('//*[@id="sider"]/div/ul/li[2]').click()
# time.sleep(2)
# driver.find_element_by_xpath('//*[@id="root"]/div/section/section/main/div/div[2]/div/div[2]/div[1]/div/div[2]/div/button[3]').click()
# time.sleep(2)
driver.close()