from selenium import webdriver
import time
driver = webdriver.Chrome()
driver.get('https://mgmt.ent-dev.kuban.io/')
driver.find_element_by_id('phone_num').send_keys('15566778899')
time.sleep(2)
driver.find_element_by_id('login_sms_code').send_keys('123456')
driver.find_element_by_xpath('//button[@type="submit"]').click()
time.sleep(13)
driver.find_element_by_xpath('//*[@id="sider"]/div/ul/li[3]/a/i').click()
time.sleep(2)
driver.find_element_by_xpath('//button[@type="submit"]').click()
time.sleep(2)
driver.find_element_by_xpath('//button[@type="text"]').send_keys('123123')
time.sleep(2)
driver.find_element_by_xpath('//*[@class="steps-action"]/dic/button[2]').send_keys('123123')
time.sleep(2)
driver.find_element_by_xpath('//button[@type="text"]').send_keys('123123')
time.sleep(2)
driver.find_element_by_xpath('/html/body/div[4]/div/div[2]/div/div/div[2]/div[2]/div/div/div[1]/button').click()
time.sleep(1)
driver.find_element_by_xpath('/html/body/div[4]/div/div[2]/div/div/div[2]/div[2]/div/div/div[1]/button').click()
time.sleep(3)
driver.close()