from base.find_element import FindElement
class LocationAdminAddActivityPage(object):
    def __init__(self,driver):
        self.fe = FindElement(driver)
    def get_activity_menu(self):
        return self.fe.get_element('activity_model')
    def get_activity_management(self):
        return self.fe.get_element('activity_list')
    def get_activity_add_btn(self):
        return self.fe.get_element('activity_addbtn')
    def get_activity_title(self):
        return self.fe.get_element('activity_title')
    def get_activity_type_input(self):
        return self.fe.get_element('activity_type_input')
    def get_activity_type(self):
        return self.fe.get_element('activity_type')
    def get_activity_time_input(self):
        return self.fe.get_element('activity_time_input')
    def get_activity_start_time(self):
        return self.fe.get_element('activity_start')
    def get_activity_end_time(self):
        return self.fe.get_element('activity_end')
    def get_activity_time_confirm(self):
        return self.fe.get_element('activity_time_sub')
    def get_activity_singup_by_end_input(self):
        return self.fe.get_element('activity_sign_date_input')
    def get_activity_signup_by_end_next_month(self):
        return self.fe.get_element('activity_sign_date_next_month')
    def get_activity_singup_by_end_time(self):
        return self.fe.get_element('activity_sign_date')
    def get_activity_space(self):
        return self.fe.get_element('activity_space')
    def get_activity_tickets(self):
        return self.fe.get_element('activity_ticket')
    def get_activity_top(self):
        return self.fe.get_element('activity_top')
    def get_activity_notop(self):
        return self.fe.get_element('activity_notop')
    def get_activity_uploadpic(self):
        return self.fe.get_element('activity_pic')
    def get_activity_note(self):
        return self.fe.get_element('activity_note')
    def get_activity_add_release(self):
        return self.fe.get_element('activity_release')
    def get_activity_add_draft(self):
        return self.fe.get_element('activity_draft')
    def get_form_tip(self):
        return self.fe.get_element('page_error_msg')
    def get_server_tip(self):
        return self.fe.get_element('server_tip_msg')
